sudo: false
dist: trusty
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
install:
  - pip install --upgrade pipenv
  - pipenv install --dev
script:
  - python setup.py install
  - coverage run --source=uk_election_ids ./run_tests.py
after_success:
  - coveralls
