dist: xenial
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
matrix:
  include:
    - python: '3.8'
      env: BLACK=1
install:
  - pip install --upgrade pip
  - pip install -e .[testing]
script:
  - coverage run --source=uk_election_ids ./run_tests.py
  - sh -c "if [ '$BLACK' = '1' ]; then pip install black ; fi"
  - sh -c "if [ '$BLACK' = '1' ]; then black --check . ; fi"
after_success:
  - coveralls
